CREATE TABLE COMMANDES (CNO INTEGER NOT NULL, FNO INTEGER, PNO INTEGER, QUANTITE INTEGER, PRIMARY KEY (CNO))
CREATE TABLE FOURNISSEURS (FNO INTEGER NOT NULL, NOM VARCHAR(255), VILLE VARCHAR(255), PRIMARY KEY (FNO))
CREATE TABLE PRODUITS (PNO INTEGER NOT NULL, LIBELLE VARCHAR(255), PRIX INTEGER, PRIMARY KEY (PNO))
